package com.sforce.soap.partner;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * Generated by SimpleTypeCodeGenerator.java. Please do not edit.
 */
public enum EmailSyncMatchPreference {


  
	/**
	 * Enumeration  : LastModified
	 */
	LastModified("LastModified"),

  
	/**
	 * Enumeration  : LastActivity
	 */
	LastActivity("LastActivity"),

  
	/**
	 * Enumeration  : Oldest
	 */
	Oldest("Oldest"),

  
	/**
	 * Enumeration  : UTF_8
	 */
	UTF_8("UTF-8"),

;

	public static Map<String, String> valuesToEnums;

	static {
   		valuesToEnums = new HashMap<String, String>();
   		for (EmailSyncMatchPreference e : EnumSet.allOf(EmailSyncMatchPreference.class)) {
   			valuesToEnums.put(e.toString(), e.name());
   		}
   	}

   	private String value;

   	private EmailSyncMatchPreference(String value) {
   		this.value = value;
   	}

   	@Override
   	public String toString() {
   		return value;
   	}
}
