package com.sforce.soap.partner.wsc;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class EmailSyncEntity implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public EmailSyncEntity() {}

    /**
     * element : conflictResolution of type {urn:partner.soap.sforce.com}EmailSyncConflictResolution
     * java type: com.sforce.soap.partner.wsc.EmailSyncConflictResolution
     */
    private static final com.sforce.ws.bind.TypeInfo conflictResolution__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","conflictResolution","urn:partner.soap.sforce.com","EmailSyncConflictResolution",1,1,true);

    private boolean conflictResolution__is_set = false;

    private com.sforce.soap.partner.wsc.EmailSyncConflictResolution conflictResolution;

    public com.sforce.soap.partner.wsc.EmailSyncConflictResolution getConflictResolution() {
      return conflictResolution;
    }

    public void setConflictResolution(com.sforce.soap.partner.wsc.EmailSyncConflictResolution conflictResolution) {
      this.conflictResolution = conflictResolution;
      conflictResolution__is_set = true;
    }

    /**
     * element : dataSetFilter of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo dataSetFilter__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","dataSetFilter","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean dataSetFilter__is_set = false;

    private java.lang.String dataSetFilter;

    public java.lang.String getDataSetFilter() {
      return dataSetFilter;
    }

    public void setDataSetFilter(java.lang.String dataSetFilter) {
      this.dataSetFilter = dataSetFilter;
      dataSetFilter__is_set = true;
    }

    /**
     * element : fieldMapping of type {urn:partner.soap.sforce.com}EmailSyncFieldMapping
     * java type: com.sforce.soap.partner.wsc.EmailSyncFieldMapping[]
     */
    private static final com.sforce.ws.bind.TypeInfo fieldMapping__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","fieldMapping","urn:partner.soap.sforce.com","EmailSyncFieldMapping",0,-1,true);

    private boolean fieldMapping__is_set = false;

    private com.sforce.soap.partner.wsc.EmailSyncFieldMapping[] fieldMapping = new com.sforce.soap.partner.wsc.EmailSyncFieldMapping[0];

    public com.sforce.soap.partner.wsc.EmailSyncFieldMapping[] getFieldMapping() {
      return fieldMapping;
    }

    public void setFieldMapping(com.sforce.soap.partner.wsc.EmailSyncFieldMapping[] fieldMapping) {
      this.fieldMapping = fieldMapping;
      fieldMapping__is_set = true;
    }

    /**
     * element : matchPreference of type {urn:partner.soap.sforce.com}EmailSyncMatchPreference
     * java type: com.sforce.soap.partner.wsc.EmailSyncMatchPreference
     */
    private static final com.sforce.ws.bind.TypeInfo matchPreference__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","matchPreference","urn:partner.soap.sforce.com","EmailSyncMatchPreference",1,1,true);

    private boolean matchPreference__is_set = false;

    private com.sforce.soap.partner.wsc.EmailSyncMatchPreference matchPreference;

    public com.sforce.soap.partner.wsc.EmailSyncMatchPreference getMatchPreference() {
      return matchPreference;
    }

    public void setMatchPreference(com.sforce.soap.partner.wsc.EmailSyncMatchPreference matchPreference) {
      this.matchPreference = matchPreference;
      matchPreference__is_set = true;
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","name","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean name__is_set = false;

    private java.lang.String name;

    public java.lang.String getName() {
      return name;
    }

    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    /**
     * element : recordTypeId of type {urn:partner.soap.sforce.com}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo recordTypeId__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","recordTypeId","urn:partner.soap.sforce.com","ID",1,1,true);

    private boolean recordTypeId__is_set = false;

    private java.lang.String recordTypeId;

    public java.lang.String getRecordTypeId() {
      return recordTypeId;
    }

    public void setRecordTypeId(java.lang.String recordTypeId) {
      this.recordTypeId = recordTypeId;
      recordTypeId__is_set = true;
    }

    /**
     * element : syncDirection of type {urn:partner.soap.sforce.com}EmailSyncDirection
     * java type: com.sforce.soap.partner.wsc.EmailSyncDirection
     */
    private static final com.sforce.ws.bind.TypeInfo syncDirection__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","syncDirection","urn:partner.soap.sforce.com","EmailSyncDirection",1,1,true);

    private boolean syncDirection__is_set = false;

    private com.sforce.soap.partner.wsc.EmailSyncDirection syncDirection;

    public com.sforce.soap.partner.wsc.EmailSyncDirection getSyncDirection() {
      return syncDirection;
    }

    public void setSyncDirection(com.sforce.soap.partner.wsc.EmailSyncDirection syncDirection) {
      this.syncDirection = syncDirection;
      syncDirection__is_set = true;
    }

    /**
     * element : syncFollowed of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo syncFollowed__typeInfo =
      new com.sforce.ws.bind.TypeInfo("urn:partner.soap.sforce.com","syncFollowed","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean syncFollowed__is_set = false;

    private boolean syncFollowed;

    public boolean getSyncFollowed() {
      return syncFollowed;
    }

    public boolean isSyncFollowed() {
      return syncFollowed;
    }

    public void setSyncFollowed(boolean syncFollowed) {
      this.syncFollowed = syncFollowed;
      syncFollowed__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, conflictResolution__typeInfo, conflictResolution, conflictResolution__is_set);
       __typeMapper.writeString(__out, dataSetFilter__typeInfo, dataSetFilter, dataSetFilter__is_set);
       __typeMapper.writeObject(__out, fieldMapping__typeInfo, fieldMapping, fieldMapping__is_set);
       __typeMapper.writeObject(__out, matchPreference__typeInfo, matchPreference, matchPreference__is_set);
       __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
       __typeMapper.writeString(__out, recordTypeId__typeInfo, recordTypeId, recordTypeId__is_set);
       __typeMapper.writeObject(__out, syncDirection__typeInfo, syncDirection, syncDirection__is_set);
       __typeMapper.writeBoolean(__out, syncFollowed__typeInfo, syncFollowed, syncFollowed__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, conflictResolution__typeInfo)) {
            setConflictResolution((com.sforce.soap.partner.wsc.EmailSyncConflictResolution)__typeMapper.readObject(__in, conflictResolution__typeInfo, com.sforce.soap.partner.wsc.EmailSyncConflictResolution.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, dataSetFilter__typeInfo)) {
            setDataSetFilter(__typeMapper.readString(__in, dataSetFilter__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, fieldMapping__typeInfo)) {
            setFieldMapping((com.sforce.soap.partner.wsc.EmailSyncFieldMapping[])__typeMapper.readObject(__in, fieldMapping__typeInfo, com.sforce.soap.partner.wsc.EmailSyncFieldMapping[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, matchPreference__typeInfo)) {
            setMatchPreference((com.sforce.soap.partner.wsc.EmailSyncMatchPreference)__typeMapper.readObject(__in, matchPreference__typeInfo, com.sforce.soap.partner.wsc.EmailSyncMatchPreference.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, name__typeInfo)) {
            setName(__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, recordTypeId__typeInfo)) {
            setRecordTypeId(__typeMapper.readString(__in, recordTypeId__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, syncDirection__typeInfo)) {
            setSyncDirection((com.sforce.soap.partner.wsc.EmailSyncDirection)__typeMapper.readObject(__in, syncDirection__typeInfo, com.sforce.soap.partner.wsc.EmailSyncDirection.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, syncFollowed__typeInfo)) {
            setSyncFollowed(__typeMapper.readBoolean(__in, syncFollowed__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[EmailSyncEntity ");
      sb.append(" conflictResolution='").append(com.sforce.ws.util.Verbose.toString(conflictResolution)).append("'\n");
      sb.append(" dataSetFilter='").append(com.sforce.ws.util.Verbose.toString(dataSetFilter)).append("'\n");
      sb.append(" fieldMapping='").append(com.sforce.ws.util.Verbose.toString(fieldMapping)).append("'\n");
      sb.append(" matchPreference='").append(com.sforce.ws.util.Verbose.toString(matchPreference)).append("'\n");
      sb.append(" name='").append(com.sforce.ws.util.Verbose.toString(name)).append("'\n");
      sb.append(" recordTypeId='").append(com.sforce.ws.util.Verbose.toString(recordTypeId)).append("'\n");
      sb.append(" syncDirection='").append(com.sforce.ws.util.Verbose.toString(syncDirection)).append("'\n");
      sb.append(" syncFollowed='").append(com.sforce.ws.util.Verbose.toString(syncFollowed)).append("'\n");
      sb.append("]\n");
      return sb.toString();
    }

}
