package com.sforce.soap.partner;

/**
 * Generated by SimpleTypeCodeGenerator.java. Please do not edit.
 */
public enum EmailSyncMatchPreference {


  /**
   * Enumeration  : LastModified
   */
   LastModified,

  /**
   * Enumeration  : LastActivity
   */
   LastActivity,

  /**
   * Enumeration  : Oldest
   */
   Oldest,


}
