package com.sforce.soap.partner;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

import java.lang.Deprecated;
/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
@Deprecated
public enum SimpleTypeEmailSyncMatchPreferenceDep {


  
	/**
	 * Enumeration  : LastModified
	 */
	LastModified("LastModified"),

  
	/**
	 * Enumeration  : LastActivity
	 */
	LastActivity("LastActivity"),

  
	/**
	 * Enumeration  : Oldest
	 */
	Oldest("Oldest"),

  
	/**
	 * Enumeration  : UTF_8
	 */
	UTF_8("UTF-8"),

;

	public static Map<String, String> valuesToEnums;

	static {
   		valuesToEnums = new HashMap<String, String>();
   		for (SimpleTypeEmailSyncMatchPreferenceDep e : EnumSet.allOf(SimpleTypeEmailSyncMatchPreferenceDep.class)) {
   			valuesToEnums.put(e.toString(), e.name());
   		}
   	}

   	private String value;

   	private SimpleTypeEmailSyncMatchPreferenceDep(String value) {
   		this.value = value;
   	}

   	@Override
   	public String toString() {
   		return value;
   	}
}
