package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class CodeLocation implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public CodeLocation() {}

    /**
     * element : column of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo column__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","column","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean column__is_set = false;

    private int column;

    public int getColumn() {
      return column;
    }

    public void setColumn(int column) {
      this.column = column;
      column__is_set = true;
    }

    /**
     * element : line of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo line__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","line","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean line__is_set = false;

    private int line;

    public int getLine() {
      return line;
    }

    public void setLine(int line) {
      this.line = line;
      line__is_set = true;
    }

    /**
     * element : numExecutions of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo numExecutions__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","numExecutions","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean numExecutions__is_set = false;

    private int numExecutions;

    public int getNumExecutions() {
      return numExecutions;
    }

    public void setNumExecutions(int numExecutions) {
      this.numExecutions = numExecutions;
      numExecutions__is_set = true;
    }

    /**
     * element : time of type {http://www.w3.org/2001/XMLSchema}double
     * java type: double
     */
    private static final com.sforce.ws.bind.TypeInfo time__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","time","http://www.w3.org/2001/XMLSchema","double",1,1,true);

    private boolean time__is_set = false;

    private double time;

    public double getTime() {
      return time;
    }

    public void setTime(double time) {
      this.time = time;
      time__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeInt(__out, column__typeInfo, column, column__is_set);
       __typeMapper.writeInt(__out, line__typeInfo, line, line__is_set);
       __typeMapper.writeInt(__out, numExecutions__typeInfo, numExecutions, numExecutions__is_set);
       __typeMapper.writeDouble(__out, time__typeInfo, time, time__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, column__typeInfo)) {
            setColumn((int)__typeMapper.readInt(__in, column__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, line__typeInfo)) {
            setLine((int)__typeMapper.readInt(__in, line__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, numExecutions__typeInfo)) {
            setNumExecutions((int)__typeMapper.readInt(__in, numExecutions__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, time__typeInfo)) {
            setTime((double)__typeMapper.readDouble(__in, time__typeInfo, double.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CodeLocation ");
      sb.append(" column=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(column)+"'\n");
      sb.append(" line=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(line)+"'\n");
      sb.append(" numExecutions=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(numExecutions)+"'\n");
      sb.append(" time=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(time)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
