package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class CodeCoverageResult implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public CodeCoverageResult() {}

    /**
     * element : id of type {http://soap.sforce.com/2006/08/apex}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","id","http://soap.sforce.com/2006/08/apex","ID",1,1,true);

    private boolean id__is_set = false;

    private java.lang.String id;

    public java.lang.String getId() {
      return id;
    }

    public void setId(java.lang.String id) {
      this.id = id;
      id__is_set = true;
    }

    /**
     * element : locationsNotCovered of type {http://soap.sforce.com/2006/08/apex}CodeLocation
     * java type: com.sforce.soap.apex.CodeLocation[]
     */
    private static final com.sforce.ws.bind.TypeInfo locationsNotCovered__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","locationsNotCovered","http://soap.sforce.com/2006/08/apex","CodeLocation",0,-1,true);

    private boolean locationsNotCovered__is_set = false;

    private com.sforce.soap.apex.CodeLocation[] locationsNotCovered = new com.sforce.soap.apex.CodeLocation[0];

    public com.sforce.soap.apex.CodeLocation[] getLocationsNotCovered() {
      return locationsNotCovered;
    }

    public void setLocationsNotCovered(com.sforce.soap.apex.CodeLocation[] locationsNotCovered) {
      this.locationsNotCovered = locationsNotCovered;
      locationsNotCovered__is_set = true;
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","name","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean name__is_set = false;

    private java.lang.String name;

    public java.lang.String getName() {
      return name;
    }

    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    /**
     * element : namespace of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo namespace__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","namespace","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean namespace__is_set = false;

    private java.lang.String namespace;

    public java.lang.String getNamespace() {
      return namespace;
    }

    public void setNamespace(java.lang.String namespace) {
      this.namespace = namespace;
      namespace__is_set = true;
    }

    /**
     * element : numLocations of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo numLocations__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","numLocations","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean numLocations__is_set = false;

    private int numLocations;

    public int getNumLocations() {
      return numLocations;
    }

    public void setNumLocations(int numLocations) {
      this.numLocations = numLocations;
      numLocations__is_set = true;
    }

    /**
     * element : numLocationsNotCovered of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo numLocationsNotCovered__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","numLocationsNotCovered","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean numLocationsNotCovered__is_set = false;

    private int numLocationsNotCovered;

    public int getNumLocationsNotCovered() {
      return numLocationsNotCovered;
    }

    public void setNumLocationsNotCovered(int numLocationsNotCovered) {
      this.numLocationsNotCovered = numLocationsNotCovered;
      numLocationsNotCovered__is_set = true;
    }

    /**
     * element : type of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo type__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","type","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean type__is_set = false;

    private java.lang.String type;

    public java.lang.String getType() {
      return type;
    }

    public void setType(java.lang.String type) {
      this.type = type;
      type__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeString(__out, id__typeInfo, id, id__is_set);
       __typeMapper.writeObject(__out, locationsNotCovered__typeInfo, locationsNotCovered, locationsNotCovered__is_set);
       __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
       __typeMapper.writeString(__out, namespace__typeInfo, namespace, namespace__is_set);
       __typeMapper.writeInt(__out, numLocations__typeInfo, numLocations, numLocations__is_set);
       __typeMapper.writeInt(__out, numLocationsNotCovered__typeInfo, numLocationsNotCovered, numLocationsNotCovered__is_set);
       __typeMapper.writeString(__out, type__typeInfo, type, type__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, id__typeInfo)) {
            setId(__typeMapper.readString(__in, id__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, locationsNotCovered__typeInfo)) {
            setLocationsNotCovered((com.sforce.soap.apex.CodeLocation[])__typeMapper.readObject(__in, locationsNotCovered__typeInfo, com.sforce.soap.apex.CodeLocation[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, name__typeInfo)) {
            setName(__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, namespace__typeInfo)) {
            setNamespace(__typeMapper.readString(__in, namespace__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, numLocations__typeInfo)) {
            setNumLocations((int)__typeMapper.readInt(__in, numLocations__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, numLocationsNotCovered__typeInfo)) {
            setNumLocationsNotCovered((int)__typeMapper.readInt(__in, numLocationsNotCovered__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, type__typeInfo)) {
            setType(__typeMapper.readString(__in, type__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CodeCoverageResult ");
      sb.append(" id=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(id)+"'\n");
      sb.append(" locationsNotCovered=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(locationsNotCovered)+"'\n");
      sb.append(" name=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(name)+"'\n");
      sb.append(" namespace=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(namespace)+"'\n");
      sb.append(" numLocations=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(numLocations)+"'\n");
      sb.append(" numLocationsNotCovered=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(numLocationsNotCovered)+"'\n");
      sb.append(" type=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(type)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
