package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class CompileTriggerResult implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public CompileTriggerResult() {}

    /**
     * element : bodyCrc of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo bodyCrc__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","bodyCrc","http://www.w3.org/2001/XMLSchema","int",0,1,true);

    private boolean bodyCrc__is_set = false;

    private int bodyCrc;

    public int getBodyCrc() {
      return bodyCrc;
    }

    public void setBodyCrc(int bodyCrc) {
      this.bodyCrc = bodyCrc;
      bodyCrc__is_set = true;
    }

    /**
     * element : column of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo column__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","column","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean column__is_set = false;

    private int column;

    public int getColumn() {
      return column;
    }

    public void setColumn(int column) {
      this.column = column;
      column__is_set = true;
    }

    /**
     * element : id of type {http://soap.sforce.com/2006/08/apex}ID
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo id__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","id","http://soap.sforce.com/2006/08/apex","ID",1,1,true);

    private boolean id__is_set = false;

    private java.lang.String id;

    public java.lang.String getId() {
      return id;
    }

    public void setId(java.lang.String id) {
      this.id = id;
      id__is_set = true;
    }

    /**
     * element : line of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo line__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","line","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean line__is_set = false;

    private int line;

    public int getLine() {
      return line;
    }

    public void setLine(int line) {
      this.line = line;
      line__is_set = true;
    }

    /**
     * element : name of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo name__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","name","http://www.w3.org/2001/XMLSchema","string",0,1,true);

    private boolean name__is_set = false;

    private java.lang.String name;

    public java.lang.String getName() {
      return name;
    }

    public void setName(java.lang.String name) {
      this.name = name;
      name__is_set = true;
    }

    /**
     * element : problem of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo problem__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","problem","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean problem__is_set = false;

    private java.lang.String problem;

    public java.lang.String getProblem() {
      return problem;
    }

    public void setProblem(java.lang.String problem) {
      this.problem = problem;
      problem__is_set = true;
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    public boolean getSuccess() {
      return success;
    }

    public boolean isSuccess() {
      return success;
    }

    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeInt(__out, bodyCrc__typeInfo, bodyCrc, bodyCrc__is_set);
       __typeMapper.writeInt(__out, column__typeInfo, column, column__is_set);
       __typeMapper.writeString(__out, id__typeInfo, id, id__is_set);
       __typeMapper.writeInt(__out, line__typeInfo, line, line__is_set);
       __typeMapper.writeString(__out, name__typeInfo, name, name__is_set);
       __typeMapper.writeString(__out, problem__typeInfo, problem, problem__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.isElement(__in, bodyCrc__typeInfo)) {
            setBodyCrc((int)__typeMapper.readInt(__in, bodyCrc__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, column__typeInfo)) {
            setColumn((int)__typeMapper.readInt(__in, column__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, id__typeInfo)) {
            setId(__typeMapper.readString(__in, id__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, line__typeInfo)) {
            setLine((int)__typeMapper.readInt(__in, line__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, name__typeInfo)) {
            setName(__typeMapper.readString(__in, name__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, problem__typeInfo)) {
            setProblem(__typeMapper.readString(__in, problem__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, success__typeInfo)) {
            setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CompileTriggerResult ");
      sb.append(" bodyCrc=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(bodyCrc)+"'\n");
      sb.append(" column=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(column)+"'\n");
      sb.append(" id=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(id)+"'\n");
      sb.append(" line=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(line)+"'\n");
      sb.append(" name=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(name)+"'\n");
      sb.append(" problem=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(problem)+"'\n");
      sb.append(" success=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(success)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
