package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class CompileClasses_element implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public CompileClasses_element() {}

    /**
     * element : scripts of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo scripts__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","scripts","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

    private boolean scripts__is_set = false;

    private java.lang.String[] scripts = new java.lang.String[0];

    public java.lang.String[] getScripts() {
      return scripts;
    }

    public void setScripts(java.lang.String[] scripts) {
      this.scripts = scripts;
      scripts__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, scripts__typeInfo, scripts, scripts__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.isElement(__in, scripts__typeInfo)) {
            setScripts((java.lang.String[])__typeMapper.readObject(__in, scripts__typeInfo, java.lang.String[].class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[CompileClasses_element ");
      sb.append(" scripts=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(scripts)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
