package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class ExecuteAnonymousResult implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public ExecuteAnonymousResult() {}

    /**
     * element : column of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo column__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","column","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean column__is_set = false;

    private int column;

    public int getColumn() {
      return column;
    }

    public void setColumn(int column) {
      this.column = column;
      column__is_set = true;
    }

    /**
     * element : compileProblem of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo compileProblem__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","compileProblem","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean compileProblem__is_set = false;

    private java.lang.String compileProblem;

    public java.lang.String getCompileProblem() {
      return compileProblem;
    }

    public void setCompileProblem(java.lang.String compileProblem) {
      this.compileProblem = compileProblem;
      compileProblem__is_set = true;
    }

    /**
     * element : compiled of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo compiled__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","compiled","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean compiled__is_set = false;

    private boolean compiled;

    public boolean getCompiled() {
      return compiled;
    }

    public boolean isCompiled() {
      return compiled;
    }

    public void setCompiled(boolean compiled) {
      this.compiled = compiled;
      compiled__is_set = true;
    }

    /**
     * element : exceptionMessage of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo exceptionMessage__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","exceptionMessage","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean exceptionMessage__is_set = false;

    private java.lang.String exceptionMessage;

    public java.lang.String getExceptionMessage() {
      return exceptionMessage;
    }

    public void setExceptionMessage(java.lang.String exceptionMessage) {
      this.exceptionMessage = exceptionMessage;
      exceptionMessage__is_set = true;
    }

    /**
     * element : exceptionStackTrace of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo exceptionStackTrace__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","exceptionStackTrace","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean exceptionStackTrace__is_set = false;

    private java.lang.String exceptionStackTrace;

    public java.lang.String getExceptionStackTrace() {
      return exceptionStackTrace;
    }

    public void setExceptionStackTrace(java.lang.String exceptionStackTrace) {
      this.exceptionStackTrace = exceptionStackTrace;
      exceptionStackTrace__is_set = true;
    }

    /**
     * element : line of type {http://www.w3.org/2001/XMLSchema}int
     * java type: int
     */
    private static final com.sforce.ws.bind.TypeInfo line__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","line","http://www.w3.org/2001/XMLSchema","int",1,1,true);

    private boolean line__is_set = false;

    private int line;

    public int getLine() {
      return line;
    }

    public void setLine(int line) {
      this.line = line;
      line__is_set = true;
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    public boolean getSuccess() {
      return success;
    }

    public boolean isSuccess() {
      return success;
    }

    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeInt(__out, column__typeInfo, column, column__is_set);
       __typeMapper.writeString(__out, compileProblem__typeInfo, compileProblem, compileProblem__is_set);
       __typeMapper.writeBoolean(__out, compiled__typeInfo, compiled, compiled__is_set);
       __typeMapper.writeString(__out, exceptionMessage__typeInfo, exceptionMessage, exceptionMessage__is_set);
       __typeMapper.writeString(__out, exceptionStackTrace__typeInfo, exceptionStackTrace, exceptionStackTrace__is_set);
       __typeMapper.writeInt(__out, line__typeInfo, line, line__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, column__typeInfo)) {
            setColumn((int)__typeMapper.readInt(__in, column__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, compileProblem__typeInfo)) {
            setCompileProblem(__typeMapper.readString(__in, compileProblem__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, compiled__typeInfo)) {
            setCompiled(__typeMapper.readBoolean(__in, compiled__typeInfo, boolean.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, exceptionMessage__typeInfo)) {
            setExceptionMessage(__typeMapper.readString(__in, exceptionMessage__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, exceptionStackTrace__typeInfo)) {
            setExceptionStackTrace(__typeMapper.readString(__in, exceptionStackTrace__typeInfo, java.lang.String.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, line__typeInfo)) {
            setLine((int)__typeMapper.readInt(__in, line__typeInfo, int.class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, success__typeInfo)) {
            setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[ExecuteAnonymousResult ");
      sb.append(" column=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(column)+"'\n");
      sb.append(" compileProblem=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(compileProblem)+"'\n");
      sb.append(" compiled=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(compiled)+"'\n");
      sb.append(" exceptionMessage=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(exceptionMessage)+"'\n");
      sb.append(" exceptionStackTrace=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(exceptionStackTrace)+"'\n");
      sb.append(" line=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(line)+"'\n");
      sb.append(" success=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(success)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
