package com.sforce.soap.apex;

/**
 * Generated by SimpleTypeCodeGenerator.java. Please do not edit.
 */
public enum LogCategoryLevel {


  /**
   * Enumeration  : Internal
   */
   Internal,

  /**
   * Enumeration  : Finest
   */
   Finest,

  /**
   * Enumeration  : Finer
   */
   Finer,

  /**
   * Enumeration  : Fine
   */
   Fine,

  /**
   * Enumeration  : Debug
   */
   Debug,

  /**
   * Enumeration  : Info
   */
   Info,

  /**
   * Enumeration  : Warn
   */
   Warn,

  /**
   * Enumeration  : Error
   */
   Error,


}
