package com.sforce.soap.apex;

/**
 * Generated by SimpleTypeCodeGenerator.java. Please do not edit.
 */
public enum LogType {


  /**
   * Enumeration  : None
   */
   None,

  /**
   * Enumeration  : Debugonly
   */
   Debugonly,

  /**
   * Enumeration  : Db
   */
   Db,

  /**
   * Enumeration  : Profiling
   */
   Profiling,

  /**
   * Enumeration  : Callout
   */
   Callout,

  /**
   * Enumeration  : Detail
   */
   Detail,


}
