package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class RunTests_element implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public RunTests_element() {}

    /**
     * element : RunTestsRequest of type {http://soap.sforce.com/2006/08/apex}RunTestsRequest
     * java type: com.sforce.soap.apex.RunTestsRequest
     */
    private static final com.sforce.ws.bind.TypeInfo RunTestsRequest__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","RunTestsRequest","http://soap.sforce.com/2006/08/apex","RunTestsRequest",1,1,true);

    private boolean RunTestsRequest__is_set = false;

    private com.sforce.soap.apex.RunTestsRequest RunTestsRequest;

    public com.sforce.soap.apex.RunTestsRequest getRunTestsRequest() {
      return RunTestsRequest;
    }

    public void setRunTestsRequest(com.sforce.soap.apex.RunTestsRequest RunTestsRequest) {
      this.RunTestsRequest = RunTestsRequest;
      RunTestsRequest__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, RunTestsRequest__typeInfo, RunTestsRequest, RunTestsRequest__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, RunTestsRequest__typeInfo)) {
            setRunTestsRequest((com.sforce.soap.apex.RunTestsRequest)__typeMapper.readObject(__in, RunTestsRequest__typeInfo, com.sforce.soap.apex.RunTestsRequest.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[RunTests_element ");
      sb.append(" RunTestsRequest=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(RunTestsRequest)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
