package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class WsdlToApexInfo implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public WsdlToApexInfo() {}

    /**
     * element : mapping of type {http://soap.sforce.com/2006/08/apex}NamespacePackagePair
     * java type: com.sforce.soap.apex.NamespacePackagePair[]
     */
    private static final com.sforce.ws.bind.TypeInfo mapping__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","mapping","http://soap.sforce.com/2006/08/apex","NamespacePackagePair",0,-1,true);

    private boolean mapping__is_set = false;

    private com.sforce.soap.apex.NamespacePackagePair[] mapping = new com.sforce.soap.apex.NamespacePackagePair[0];

    public com.sforce.soap.apex.NamespacePackagePair[] getMapping() {
      return mapping;
    }

    public void setMapping(com.sforce.soap.apex.NamespacePackagePair[] mapping) {
      this.mapping = mapping;
      mapping__is_set = true;
    }

    /**
     * element : wsdl of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String
     */
    private static final com.sforce.ws.bind.TypeInfo wsdl__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","wsdl","http://www.w3.org/2001/XMLSchema","string",1,1,true);

    private boolean wsdl__is_set = false;

    private java.lang.String wsdl;

    public java.lang.String getWsdl() {
      return wsdl;
    }

    public void setWsdl(java.lang.String wsdl) {
      this.wsdl = wsdl;
      wsdl__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, mapping__typeInfo, mapping, mapping__is_set);
       __typeMapper.writeString(__out, wsdl__typeInfo, wsdl, wsdl__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.isElement(__in, mapping__typeInfo)) {
            setMapping((com.sforce.soap.apex.NamespacePackagePair[])__typeMapper.readObject(__in, mapping__typeInfo, com.sforce.soap.apex.NamespacePackagePair[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, wsdl__typeInfo)) {
            setWsdl(__typeMapper.readString(__in, wsdl__typeInfo, java.lang.String.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[WsdlToApexInfo ");
      sb.append(" mapping=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(mapping)+"'\n");
      sb.append(" wsdl=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(wsdl)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
