package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class WsdlToApexResult implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public WsdlToApexResult() {}

    /**
     * element : apexScripts of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo apexScripts__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","apexScripts","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

    private boolean apexScripts__is_set = false;

    private java.lang.String[] apexScripts = new java.lang.String[0];

    public java.lang.String[] getApexScripts() {
      return apexScripts;
    }

    public void setApexScripts(java.lang.String[] apexScripts) {
      this.apexScripts = apexScripts;
      apexScripts__is_set = true;
    }

    /**
     * element : errors of type {http://www.w3.org/2001/XMLSchema}string
     * java type: java.lang.String[]
     */
    private static final com.sforce.ws.bind.TypeInfo errors__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","errors","http://www.w3.org/2001/XMLSchema","string",0,-1,true);

    private boolean errors__is_set = false;

    private java.lang.String[] errors = new java.lang.String[0];

    public java.lang.String[] getErrors() {
      return errors;
    }

    public void setErrors(java.lang.String[] errors) {
      this.errors = errors;
      errors__is_set = true;
    }

    /**
     * element : success of type {http://www.w3.org/2001/XMLSchema}boolean
     * java type: boolean
     */
    private static final com.sforce.ws.bind.TypeInfo success__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","success","http://www.w3.org/2001/XMLSchema","boolean",1,1,true);

    private boolean success__is_set = false;

    private boolean success;

    public boolean getSuccess() {
      return success;
    }

    public boolean isSuccess() {
      return success;
    }

    public void setSuccess(boolean success) {
      this.success = success;
      success__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, apexScripts__typeInfo, apexScripts, apexScripts__is_set);
       __typeMapper.writeObject(__out, errors__typeInfo, errors, errors__is_set);
       __typeMapper.writeBoolean(__out, success__typeInfo, success, success__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.isElement(__in, apexScripts__typeInfo)) {
            setApexScripts((java.lang.String[])__typeMapper.readObject(__in, apexScripts__typeInfo, java.lang.String[].class));
        }
        __in.peekTag();
        if (__typeMapper.isElement(__in, errors__typeInfo)) {
            setErrors((java.lang.String[])__typeMapper.readObject(__in, errors__typeInfo, java.lang.String[].class));
        }
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, success__typeInfo)) {
            setSuccess(__typeMapper.readBoolean(__in, success__typeInfo, boolean.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[WsdlToApexResult ");
      sb.append(" apexScripts=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(apexScripts)+"'\n");
      sb.append(" errors=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(errors)+"'\n");
      sb.append(" success=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(success)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
