package com.sforce.soap.apex;

/**
 * Generated by ComplexTypeCodeGenerator.java. Please do not edit.
 */
public class WsdlToApex_element implements com.sforce.ws.bind.XMLizable {

    /**
     * Constructor
     */
    public WsdlToApex_element() {}

    /**
     * element : info of type {http://soap.sforce.com/2006/08/apex}WsdlToApexInfo
     * java type: com.sforce.soap.apex.WsdlToApexInfo
     */
    private static final com.sforce.ws.bind.TypeInfo info__typeInfo =
      new com.sforce.ws.bind.TypeInfo("http://soap.sforce.com/2006/08/apex","info","http://soap.sforce.com/2006/08/apex","WsdlToApexInfo",1,1,true);

    private boolean info__is_set = false;

    private com.sforce.soap.apex.WsdlToApexInfo info;

    public com.sforce.soap.apex.WsdlToApexInfo getInfo() {
      return info;
    }

    public void setInfo(com.sforce.soap.apex.WsdlToApexInfo info) {
      this.info = info;
      info__is_set = true;
    }

    /**
     */
    @Override
    public void write(javax.xml.namespace.QName __element,
        com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper)
        throws java.io.IOException {
      __out.writeStartTag(__element.getNamespaceURI(), __element.getLocalPart());
      writeFields(__out, __typeMapper);
      __out.writeEndTag(__element.getNamespaceURI(), __element.getLocalPart());
    }

    protected void writeFields(com.sforce.ws.parser.XmlOutputStream __out,
         com.sforce.ws.bind.TypeMapper __typeMapper)
         throws java.io.IOException {
       __typeMapper.writeObject(__out, info__typeInfo, info, info__is_set);
    }

    @Override
    public void load(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
      __typeMapper.consumeStartTag(__in);
      loadFields(__in, __typeMapper);
      __typeMapper.consumeEndTag(__in);
    }

    protected void loadFields(com.sforce.ws.parser.XmlInputStream __in,
        com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
        __in.peekTag();
        if (__typeMapper.verifyElement(__in, info__typeInfo)) {
            setInfo((com.sforce.soap.apex.WsdlToApexInfo)__typeMapper.readObject(__in, info__typeInfo, com.sforce.soap.apex.WsdlToApexInfo.class));
        }
    }

    @Override
    public String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder();
      sb.append("[WsdlToApex_element ");
      sb.append(" info=");
      sb.append("'"+com.sforce.ws.util.Verbose.toString(info)+"'\n");
      sb.append("]\n");
      return sb.toString();
    }
}
