name: Clean Up Old Release Branches

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clean Up Old Release Branches
        uses: actions/github-script@v6
        with:
          script: |
            const daysToKeep = 14;
            const releaseBranchPattern = /^release-v\d+\.\d+$/;
            
            const branches = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const now = new Date();

            for (const branch of branches.data) {
              if (releaseBranchPattern.test(branch.name)) {
                const branchInfo = await github.rest.repos.getBranch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: branch.name,
                });

                const branchDate = new Date(branchInfo.data.commit.commit.author.date);
                const ageInDays = (now - branchDate) / (1000 * 60 * 60 * 24);

                if (ageInDays > daysToKeep) {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `heads/${branch.name}`,
                  });
                  console.log(`Deleted branch: ${branch.name}`);
                }
              }
            }
